apiVersion: v1
kind: Secret
metadata:
  name: stakevault-secrets
type: Opaque
stringData:
  POSTGRES_AUTH_PASSWORD: CHANGE_ME
  POSTGRES_BETS_PASSWORD: CHANGE_ME
  POSTGRES_STATS_PASSWORD: CHANGE_ME
  RABBITMQ_USER: CHANGE_ME
  RABBITMQ_PASSWORD: CHANGE_ME
  REDIS_PASSWORD: CHANGE_ME
  N8N_ENCRYPTION_KEY: CHANGE_ME
  PASETO_LOCAL_KEY: CHANGE_ME
  ADMIN_API_KEY: CHANGE_ME
  SERVICE_KEY: CHANGE_ME
